Vagrant.configure(2) do |config|
  config.vm.box = "ubuntu/trusty64"
  config.vm.hostname ="NodeEx"
  config.vm.provision "shell", path: "provision.sh" 
  config.vm.network "forwarded_port", guest:8000, host:8080, id: "WevEnv1"
  config.vm.network "forwarded_port", guest:8001, host:8081, id: "WevEnv2"
  config.vm.network "forwarded_port", guest:8002, host:8082, id: "WevEnv3"
  config.vm.network "forwarded_port", guest:8003, host:8083, id: "WevEnv4"
  config.vm.network "forwarded_port", guest:8004, host:8084, id: "WevEnv5"
  config.vm.network "forwarded_port", guest:8005, host:8085, id: "WevEnv6"
  config.vm.network "forwarded_port", guest:27017, host:8100, id: "Mongodb"
  config.vm.network "forwarded_port", guest:28017, host:8101, id: "MongodbREST"

end
